### ISSUE TITLE
Version checking required for OpenCV version / Error checking if it can't handle operation

### ISSUE THREAD

**Issue by dsowsy** [CloudCV/cloudcv-bootstrap#9]
After doing npm install, it shows the animal and doesn't actually extract the colors. 
After dragging/dropping an arbitrary image into the browser it doesn't do anything at all. 

POST http://10.0.0.3:3000/api/v1/image/analyze/dominantColors/  404 (Not Found)

**Comment by esnho** [comment]
In mine istallation (Mac Pro 10.11.2) I've got the same issue.
I've also tested on a Cloud9 service
npm test doesn't returns any error

The browser console returns:

https://aaa-lmoroni.c9users.io/api/v1/image/analyze/dominantColors/ Failed to load resource: the server responded with a status of 404 (Not Found)

?_c9_id=livepreview0&_c9_host=https://ide.c9.io:31 Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.

**Comment by esnho** [comment]
And this is in localhost

jquery-2.0.3.min.js:6 POST http://localhost:3000/api/v1/image/analyze/dominantColors/ 404 (Not Found)x.support.cors.e.crossDomain.send @ jquery-2.0.3.min.js:6x.extend.ajax @ jquery-2.0.3.min.js:6dominantColors @ cloudcv.js:24extractDominantColorsFromFile @ (index):31(anonymous function) @ (index):121x.event.dispatch @ jquery-2.0.3.min.js:5y.handle @ jquery-2.0.3.min.js:5
(index):31 

Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.

**Comment by ekhvedchenya-daqri** [comment]
Hi @esnho . Will check

**Comment by BloodAxe** [comment]
Hi. The master branch containing updated version. What you are looking for, is available at this commit:
https://github.com/CloudCV/cloudcv-bootstrap/tree/44820f4ba3741e667192c374f802149b962a0d36

After this point, things get messed up and changed almost totally. I realised that doing type checking on JS side is pain, so instead I moved this to C++ with some neat features like automatic algorithm properties registration. The ultimate goal was to do as much as possible on C++ side.
It was done partially -  I managed to implement C++ type checking and properties registration, but due to a quick evolution of Nodejs and lack of time, I don't have enough time to keep this project up-to-date.
